server:
  port: 8001
spring:

  application:
    name: Video-Russell

  devtools:
    livereload:
      enabled: true

  datasource:
    url: ${RUSSELL_VIDEO_DB_URL:jdbc:mysql://localhost:3306/wechat_video?useUnicode=true&characterEncoding=utf8&useSSL=false}
    username: ${RUSSELL_VIDEO_DB_NAME:root}
    password: ${RUSSELL_VIDEO_DB_PASSWORD:92QWWQ0828MM}
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:import.sql

  freemarker:
    check-template-location: false

mybatis:
  typeAliasesPackage: com.russell.video.mapper
  mapperLocations: classpath:mapper/**/*.xml

logging:
  level:
    root: warn
    com.russell.video.mapper: debug

myprops:
  appId: wx01a775894f92bb9d
  appSecret: 4a3c23d29896ba03583ee6ce9c37b07d
  appToken: iudei837h48js
  appKey: kG7KxdshQCduNnTEjI8tmEYQZVPDeQ9iXQzm7ECyYS2
  appUrl: http://oauth.saas.biosan.cn/
  weChatAddress: https://api.weixin.qq.com
  userSessionTimeout: 1800
  weChatLoginUrl: https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code


