server:
  port: 8000
spring:

  application:
    name: Video-Russell

  devtools:
    livereload:
      enabled: true

  datasource:
    url: ${RUSSELL_VIDEO_DB_URL:jdbc:mysql://localhost:3306/wechat_video?useUnicode=true&characterEncoding=utf8&useSSL=false}
    username: ${RUSSELL_VIDEO_DB_NAME:root}
    password: ${RUSSELL_VIDEO_DB_PASSWORD:92QWWQ0828MM}
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:import.sql

  freemarker:
    check-template-location: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

logging:
  level:
    root: warn
    com.russell.video.mapper: debug

myprops:
  componentid: wx01a775894f92bb9d
  componentsecret: e82cd0790f947906a0c6da935eb3b5b3
  componenttoken: iudei837h48js
  componentkey: kG7KxdshQCduNnTEjI8tmEYQZVPDeQ9iXQzm7ECyYS2
  componenturl: http://oauth.saas.biosan.cn/
  authorizerappid: wx01a775894f92bb9d
  wechataddress: https://api.weixin.qq.com
  mobilefromid: ${spring.application.name}${server.port}
  usersessiontimeout: 1800


